object Versions {
    const val androidKtx = "1.7.0"
    const val androidxLifecycle = "2.5.1"
    const val activityCompose = "1.5.1"
    const val compose = "1.2.1"
    const val navigation = "2.5.2"
    const val hilt = "2.43"
    const val hiltNavCompose = "1.0.0"
    const val room = "2.4.3"
    const val material = "1.2.1"
    const val junit = "4.13.2"
    const val androidxJunit = "1.1.3"
    const val espresso = "3.4.0"
    const val gson = "2.9.1"
    const val timber = "5.0.1"
    const val moshi = "1.8.0"
    const val moshiConverter = "2.9.0"
    const val mapsCompose = "2.7.2"
    const val playServiceMaps = "18.1.0"
    const val retrofit = "2.9.0"
    const val coroutineAdapter = "0.9.2"

    const val firebaseBom = "30.5.0"
    const val firebaseCore = "21.1.1"
    const val firebaseAuth = "21.0.8"
    const val firebaseCrashlytics = "18.2.13"
    const val firebaseAnalytics = "21.1.1"
}